services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: department_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=department_management
      - DB_PORT=5432
      - JWT_SECRET=apartment_management_jwt_secret_key_2025
      - JWT_EXPIRE=24h
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - postgres
    networks:
      - app-network
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
